# Generated by Django 3.2.19 on 2023-07-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
